name: aux-flow

on:
  workflow_dispatch:

#on:
#  push:
#    branches:    
#      - main

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v3
    - name: Check stack name
      run: |
        ls ${{ github.workspace }}/services/**/*json

        echo "-----------"

        for STACK in $(ls services/**/*json)
        do
                OUTPUT+="- $STACK\n          "
        done

        sed "s/options:/options:\n\t${OUTPUT}/" .github/workflows/otro_action.yml
        echo $OUTPUT
        
    #- name: Run the Action
    #  uses: devops-infra/action-commit-push@master
    #  with:
    #    github_token: "${{ secrets.GITHUB_TOKEN }}"
    #    add_timestamp: true
    #    commit_prefix: "[AUTO]"
    #    commit_message: "Automatic commit"
    #    force: false
    #    target_branch: update/version

