name: aux-flow

on:
  workflow_dispatch:

#on:
#  push:
#    branches:    
#      - main

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v3
    - name: Check stack name
      run: |
        ls ${{ github.workspace }}/services/**/*json

        ## Get all presently existing stacks (all items between options and jobs with a dash in the line)
        sed -n '/options/,/jobs/p' .github/workflows/otro_action.yml | grep '-' | tr -dc '[:alnum:]\n\r\t' | sort | uniq > OLDS

        ## Get all services in greensea 
        ls services/**/stack_manifest.json | rev | cut -d'/' -f 2 | rev | sort | uniq > NEWS

        ## Comm 
        comm -1 <(sed -n '/options/,/jobs/p' .github/workflows/otro_action.yml | grep '-' | tr -dc '[:alnum:]\n\r\t' | sort | uniq) <(ls services/**/stack_manifest.json | rev | cut -d'/' -f 2 | rev | sort | uniq)
        
        ## Compares the stacks in the actions script vs the stacks found in the services directory, if there is a difference sets update to 1 to add the missing (replace entire block so supports deleting stacks)
        comm -3 <(sed -n '/options/,/jobs/p' .github/workflows/otro_action.yml | grep '-' | tr -dc '[:alnum:]\n\r\t' | sort | uniq) <(ls services/**/stack_manifest.json | rev | cut -d'/' -f 2 | rev | sort | uniq) | wc -l

        echo "-----------"

        for STACK in $(ls services/**/*json)
        do
                OUTPUT+="- $STACK\n          "
        done

        sed "s/options:/options:\n\t${OUTPUT}/" .github/workflows/otro_action.yml
        echo $OUTPUT
        
    #- name: Run the Action
    #  uses: devops-infra/action-commit-push@master
    #  with:
    #    github_token: "${{ secrets.GITHUB_TOKEN }}"
    #    add_timestamp: true
    #    commit_prefix: "[AUTO]"
    #    commit_message: "Automatic commit"
    #    force: false
    #    target_branch: update/version

