name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      stack_name:
        required: true

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Check stack name
      run: echo "${{ github.event.inputs.stack_name }}"
