name: aux-flow

on:
  workflow_dispatch:

#on:
#  push:
#    branches:    
#      - main

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v3
    - name: Check stack name
      run: |
        ls ${{ github.workspace }}/services/**/*json

        ## Get a list of stacks listed in the yaml and a list of stacks in the source code
        FILE_STACKS=$(sed -n '/options/,/jobs/p' .github/workflows/otro_action.yml | grep '-' | tr -dc '[:alnum:]\n\r\t' | sort | uniq)
        SRC_STACKS=$(ls services/**/stack_manifest.json | rev | cut -d'/' -f 2 | rev | sort | uniq)

        echo "Reg stacks ${FILE_STACKS}"
        echo "Src stacks ${SRC_STACKS}"

        ## Compare to detect changes
        UPDATE = $(comm -3 <(echo $FILE_STACKS) <(echo $SRC_STACKS) | wc -l)

        if [[ $UPDATE -ge 1 ]]
        then
          echo "New stack found, updating yaml"
          for STACK in $SRC_STACKS
          do
            OUTPUT+="- $STACK\n          "
          done
        fi

        #sed "s/options:/options:\n\t${OUTPUT}/" .github/workflows/otro_action.yml
        echo $OUTPUT
        
    #- name: Run the Action
    #  uses: devops-infra/action-commit-push@master
    #  with:
    #    github_token: "${{ secrets.GITHUB_TOKEN }}"
    #    add_timestamp: true
    #    commit_prefix: "[AUTO]"
    #    commit_message: "Automatic commit"
    #    force: false
    #    target_branch: update/version

