name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      stack_name:
        required: true

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v3
    - name: Check stack name
      run: |
        ls ${{ github.workspace }}/services/**/*json
