name: Main-flow

on:
  workflow_dispatch:
    esta_variable:
      required: true
      type: choice
      options:
        - info
        - debug

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Check stack name
      run: |
        echo ${{ inputs.esta_variable }}