name: Main-flow

on:
  workflow_dispatch:
    esta_variable:
      required: true
      type: choice
      options:
        - stack1
        - stack2

jobs:
  run_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Check stack name
      run: |
        echo ${{ inputs.esta_variable }}One more line at ...
One more line at ...
One more line at ...
One more line at ...
One more line at ...
One more line at ...
One more line at ...
One more line at ...
