name: vairables wrangling

on:
  workflow_dispatch:
  
jobs:
  set-variable:
    runs-on: ubuntu-latest

    outputs:
      variable1: ${{steps.setv.outputs.variable1}}

    steps:
      - name: setv
        id: setv
        run: |
          echo "variable1=1" >> $GITHUB_OUTPUT
  
  read_variable:
    runs-on: ubuntu-latest
    needs: set-variable
    steps:
      - env:
          OUTPUT1: ${{ needs.set-variable.outputs.vairable1 }}
        run: |
          echo "echoing the variable"
          echo $OUTPUT1