name: vairables wrangling

on:
  workflow_dispatch:
  push:
    
jobs:
  set-variable:
    runs-on: ubuntu-latest

    outputs:
      variable1: ${{ steps.set-variable.outputs.variable1 }}

    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: set-variable
        id: set-variable
        run: |
          echo "variable1=1" >> $GITHUB_OUTPUT
          variable2=2
      
      - name: despues
        id: despues
        run: |
          echo "Varible es ${{ steps.set-variable.outputs.variable1 }} "
          echo "One more line at ..." >> .github/workflows/otro_action.yaml

      - name: checkin
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          commit_message: "Yaml list update"

  #read_variable:
  #  runs-on: ubuntu-latest
  #  needs: set-variable
  #  steps:
  #    - env:
  #        OUTPUT1: ${{ needs.set-variable.outputs.variable1 }}
  #      run: |
  #        echo "echoing the variable"
  #        echo ${{ needs.set-variable.outputs.variable1 }}
  #        echo $OUTPUT1

